#!/bin/sh

if [ "$1" == "start" -o "$1" == "start_eth0" ]
then
	ifconfig eth0:0 192.168.0.99
	ifconfig eth0:1 192.168.1.99
	dhcpcd eth0 &
fi

if [ "$1" == "start" -o "$1" == "start_usb0" ]
then
	modprobe g_ether
	ifconfig usb0 192.168.2.99
	dnsmasq -z -a 192.168.2.99 -F 192.168.2.100,192.168.2.200 -l /var/log/dnsmasq.usb0.leases
fi

if [ "$1" == "start_wlan0_station" -o "$1" == "start_wlan0_ap" ]
then
	PID_DNSMASQ=`ps aux | grep dnsmasq | grep wlan0 | grep -v grep | awk '{print $1}'`
	[ "$PID_DNSMASQ" == "" ] || kill $PID_DNSMASQ

	PID_HOSTAPD=`ps aux | grep hostapd | grep -v grep | awk '{print $1}'`
	[ "$PID_HOSTAPD" == "" ] || kill $PID_HOSTAPD

	PID_WPA_SUPPLICANT=`ps aux | grep wpa_supplicant | grep -v grep | awk '{print $1}'`
	[ "$PID_WPA_SUPPLICANT" == "" ] || kill $PID_WPA_SUPPLICANT

	dhcpcd --release wlan0
fi

if [ "$1" == "start_wlan0_station" ]
then
	wpa_passphrase "$2" "$3" | grep -v '#psk' > /tmp/wpa.conf

	wpa_supplicant -c /tmp/wpa.conf -i wlan0 &
	dhcpcd wlan0 &
fi

if [ "$1" == "start" -o "$1" == "start_wlan0_ap" ]
then
	modprobe rt2800usb
	WLAN=$(ifconfig wlan0 >/dev/null 2>&1; echo $?)
	if [ $WLAN == 0 ]
	then
		ifconfig wlan0 192.168.3.99
		hostapd -B /etc/hostapd.conf
		dnsmasq -z -a 192.168.3.99 -F 192.168.3.100,192.168.3.200 -l /var/log/dnsmasq.wlan0.leases
	fi
fi

exit $?
